Repository centreon/centreon-gorgone, pull requests merged in 2022-07, with the labels that each got.

#250 fix(mbi): stuck if there is an issue during the planning
  gorgone/modules/centreon/mbi/etl/class.pm
Labels: bug

#253 (plugins) add rocky linux support
  gorgone/modules/centreon/audit/metrics/centreon/packages.pm
  gorgone/modules/core/action/class.pm
Labels: enhancement

#255 Merge release-debian-22.04.0 into 22.04.x
  Jenkinsfile
  ci/debian/centreon-gorgone.postinst
  contrib/gorgone_install_plugins.pl
  gorgone/modules/core/action/class.pm
Labels: area/backend

#256 fix(wss): change header token name + token ending regexp (MON-14426)
  gorgone/modules/core/proxy/httpserver.pm
  gorgone/modules/core/pullwss/class.pm
Labels: bug
