Repository centreon/centreon-gorgone, pull requests merged in 2022-05, with the labels that each got.

#231 enh: handle almalinux os for audit and plugins install
  gorgone/modules/centreon/audit/metrics/centreon/packages.pm
  gorgone/modules/core/action/class.pm
Labels: enhancement

#232 enh(legacy): cbd reload after remote-server import
  gorgone/modules/centreon/legacycmd/class.pm
Labels: bug

#233 enh: handle oracle linux os for audit and plugins install
  gorgone/modules/centreon/audit/metrics/centreon/packages.pm
  gorgone/modules/core/action/class.pm
Labels: enhancement

#236 enh: handle rhel os for audit and plugins install
  gorgone/modules/centreon/audit/metrics/centreon/packages.pm
  gorgone/modules/core/action/class.pm
Labels: enhancement

#239 chore(install): update version to 20.10.7
  packaging/centreon-gorgone.spectemplate
Labels: area/backend
